### ISSUE TITLE
Current grid export 

### ISSUE THREAD

**Issue by crescentit** [GitHub4Eddy/solaredge_monitor#1]
Howdy,

It would be very helpful if this Quick App could pull the current export amount. This measure of excess generation could be used as a trigger to start applicances such as hot water element or under floor heating.

Thanks

**Comment by GitHub4Eddy** [comment]
Hi,

I think you need the SolarEdge Inline Energymeter for that. 

https://www.solaredge.com/nl/products/solaredge-inline-meter#/

**Comment by GitHub4Eddy** [comment]
Without the SolarEdge Inline Energymeter, I use the P1 monitor quickapp to measure consumption and production. If the production child device is greater than zero, you have export to the grid. 

If you can measure the total consumption of your house, you could calculate the excess generation.

**Comment by crescentit** [comment]
Thanks for pointing out the P1 monitor, I'll take a look. Seems like that's extra software required though.

My Solaredge Energy Hub appears to have all the required meters, and the mySolarEdge app displays my grid export values in real time. 

Looking at the SolarEdge API, I think it should be able to retrieve these values?

e.g.

**Site Power Flow**
Description: Retrieves the current power flow between all elements of the site including PV array, storage (battery), loads
(consumption) and grid.
Note: Applies when export , import and consumption can be measured.
URL: /site/{siteId}/currentPowerFlow

 Response: The response returns power flow for each of the elements in the system and their state.
In case the site does not support this information, the response should be an empty object.
Otherwise, the response includes the following:
• siteCurrentPowerFlow - Root element
• unit - The measurement units (e.g. Watt)
• connections - A table including all the relationships between the elements, and the power flow
directions (producing element and consuming element)
• from element - The element providing power
• to element - The element consuming power
• A list of elements - Element per entity type in the specific site
• GRID - always included in response
• LOAD - always included in response
• PV - included if the site has a PV array (measurement of PV produced power)
• STORAGE - included if the site has storage installed and enabled

Loving the Quick App and thanks for sharing. Will suss out P1 Monitor as another option.

**Comment by GitHub4Eddy** [comment]
You need the SolarEdge Inline Energymeter or indeed the new Solaredge Energy Hub. Both need a different quickapp with a different approach compared to the SolarEdge Monitor. I tried to get the SolarEdge Inline Energymeter, but that didn’t happen unfortunately.
